# SITE CONFIGURATION
title: Y.C. Tseng's Site # your site title
author: YCTs # You :P
description: > # Meta description of Homepage
  定期整理一些論文筆記以及學習心得
baseurl: "/weeklypapers" # the subpath of your site, e.g. /blog
url: "https://ycts.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# SEO PLUGIN
social:
  name: Y.C. Tseng
  links:
    - https://www.facebook.com/profile.php?id=100009242093014


# THEME SETTINGS
navigation: # Navigation links
  - {name: 'Home', link: '/'}
  - {name: 'Categories', link: '/categories'}
  - {name: 'About', link: '/about'}
  - {name: 'Contact', link: '/contact'}

tagline: >
  Knowledge makes humble, ignorance makes proud.

hero_img: posts/sleek_lg.jpg # Main background image: use the path from /assets/img/ => This will output /assets/img/posts/sleek_lg.jpg

email: b03505053@ntu.edu.tw # email for form submission

#twitter_username: jan_czizikow # replace with your_twitter_username or comment to remove link from footer
github_username:  YCTs # replace with your_github_username or comment to remove link from footer
instagram_username: yct666 # replace with your_instagram_username or comment to remove link from footer

disqus:
  shortname: https-ycts-github-io-weeklypapers # to enable comments replace with your_disqus_shortname

# google_tag_manager: GTM-XXXXXXX # Uncomment to enable GTM. Replace GTM-XXXXXXX with your GTM container ID

service_worker: true

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge # or pygments or null
remote theme: jekyll-sleek # Uncomment if you're using the theme as a ruby gem
exclude:
  - README.md
  - node_modules
  - script
  - package.json
  - package-lock.json
  - Gemfile
  - Gemfile.lock
  - vendor
  - npm-debug.log
  - gulpfile.js
  - sleek.jpg

include: ['_pages']
permalink: /:title/

compress_html:
  clippings: all

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
